name: bot-deploy
on:
  push:
    branches:
      - main
    paths:
      - bot/*
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  docker-build-and-push:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
  
      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bot-image:${{ github.event.number }}
      #   working-directory: bot

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [docker-build-and-push]
    environment:
      name: bot
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Test
        run: echo test
